version: "3.9"

services:
  lighthouse1:
    image: narvikd/nebula:1.6.1
    container_name: nebula-lighthouse1
    command: -config /app/config-lighthouse.yaml
    network_mode: "host"
    ports:
      - '5252:5252'
    volumes:
      - /srv/data/nebula:/app
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: on-failure
